version: '2'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - '16686:16686'
  collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ['--config=/etc/otel-collector-config.yaml']
    volumes:
      - ./collector/config.yaml:/etc/otel-collector-config.yaml
    depends_on:
      - jaeger
  nginx:
    build: ./nginx
    platform: linux/amd64
    ports:
      - '8002:80'
    volumes:
      - ./nginx/opentelemetry_module.conf:/etc/nginx/conf.d/opentelemetry_module.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4317/
    depends_on:
      - apache
  apache:
    build: ./apache
    platform: linux/amd64
    ports:
      - '8001:80'
    environment:
    # settings below are for the PHP tier, apache takes config from opentelemetry_moduel.conf
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=none
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4318/
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_SERVICE_NAME=backend
  frontend:
    build: ./frontend
    ports:
      - '8000:8000'
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4318/
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_SERVICE_NAME=frontend
    depends_on:
      - nginx
  loadgen:
    build: ./loadgen
    environment:
      - URL=http://frontend:8000/
  teletrace:
    image: teletrace/teletrace:latest
    ports:
      - '8080:8080'
      - '9200:9200'
    command: ['--config=/etc/teletrace-config.yaml']
    volumes:
      - ./teletrace/config.yaml:/etc/teletrace-config.yaml
    environment:
      - SPANS_STORAGE_PLUGIN=sqlite
    
